name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  search_app_bar_page: ^2.5.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/user.png
    - assets/icons/home.png
    - assets/icons/heart.png
    - assets/icons/shopping-cart.png
    - assets/icons/search.png
    - assets/icons/drawer.png
    - assets/icons/hand-wave.png
